user_path = "data/users.json"
budget_path = "data/budgets.json"
super_transaction_path = "data/super_transactions.json"
account_path = "data/accounts.json"
super_category_path = "data/super_categories.json"
category_path = "data/categories.json"
assignment_path = "data/assignments.json"
transaction_path = "data/transactions.json"
payee_path = "data/payees.json"
currency_path = "data/currencies.json"
